#server:
#  port: 8761
#eureka:
#  client:
#    # 是否要注册到其他Eureka Server实例
#    register-with-eureka: false
#    # 是否要从其他Eureka Server实例获取数据
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-discovery-eureka-ha

  security:
    user:
      name: user                # 配置登录的账号是user
      password: password123     # 配置登录的密码是password123

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/

---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
